application: noble-freehold-326
version: 1
api_version: 1
runtime: python27
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /profile/.*
  script: user_profile.py
  login: required
  auth_fail_action: unauthorized

- url: /admin/.*
  script: admin.py
  login: admin
  
- url: /static
  static_dir: static
  
- url: /images
  static_dir: images
  
- url: /sqlscripts
  static_dir: sqlscripts
  
- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest